### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by far-galaxy** [far-galaxy/l9_stud_bot#18]
Сайт Tickgit не хочет работать, поэтому делаю выписку тудушек сюда:

# Рефакторинг
- [ ] Добавить проверку изменений в полях данных
  => modules/ssau_parser/database.go:92:3

- [ ] Создать тип таких префиксов
  => modules/tg/shedule.go:125:6

- [ ] Избавиться от повторяющихся конструкций
  => modules/tg/handlers.go:248:5

- [ ] Завернуть в структуру
  => modules/tg/bot.go:29:3

- [ ] Придумать скачки для пустых дней
  => modules/tg/shedule.go:186:5

- [ ] Загнать эту конструкцию внутрь функции
  => modules/tg/week_shedule.go:281:4

- [ ] Изобрести раздорбление логов по дате
  => modules/database/mysql.go:86:3

# Фунцкионал
- [ ] Проверять подключенные ранее расписания
  => modules/tg/handlers.go:115:5

- [ ] Реализовать нормальное обновление фото, когда нужный метод появится в tgbotapi
  => modules/tg/utils.go:160:6

- [ ] Сделать костыль поизящнее и предупреждать, если неделя пустая
  => modules/tg/week_shedule.go:141:5

- [ ] Перескакивать окна
  => modules/notify/notify.go:120:4

- [ ] Установить время удаления на момент сообщения о начале пар
  => modules/notify/notify.go:192:6

- [ ] Проработать разные подгруппы
  => modules/notify/notify.go:200:5

# Критическое
- [ ] #15 
  => main.go:55:4

- [ ] Обрабатывать старые сообщения, которые уже нельзя редактировать (message can't be deleted for everyone)
  => modules/tg/utils.go:143:3
